language: php

php:
  - 7.1

services:
  - rabbitmq

install:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - composer test -- --coverage-text --coverage-clover=coverage.clover --verbose $PHPUNIT_FLAGS
